[project]
name = "gemz"
version = "0.0.1"
dependencies = [
  "rpy2",
  "numpy",
  "scikit-learn",
  "jax <= 0.3.7", # breaks distrax
  "jaxlib <= 0.3.7", # matches jax
  "distrax"
]

[build-system]
requires = [
  "setuptools >= 40.8.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
