[project]
name = "gemz"
version = "0.0.1"
dependencies = [
  "numpy",
  "scipy",
  "scikit-learn",
  "jax <= 0.3.7", # breaks distrax
  "jaxlib <= 0.3.7", # matches jax
  "distrax",
  "rpy2",
  "deprecation",
]

[project.optional-dependencies]
peer = [
  "pmbio-peer @ git+ssh://git@github.com/emorice/peer.git"
]
dev = [
  "memory_profiler"
]

[build-system]
requires = [
  "setuptools >= 40.8.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
