name: Tests

# Adapted from the default python action at
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 2'
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'
      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel
          git config --global url."https://ssh:${{secrets.GH_PAT}}@github.com/".insteadOf 'ssh://git@github.com/'
          git config --global url."https://git:${{secrets.GH_PAT}}@github.com/".insteadOf 'git@github.com:'
          pip install .[test] ./gemz-galp[test]
      - name: Test
        run: |
          pytest -k 'not nonlinear_shrinkage and not peer' -v --no-cov
